version: '3.9'

services:
  tarantool:
    image: tarantool/tarantool:latest
    container_name: tarantool
    ports:
      - "3301:3301"
    volumes:
      - tarantool_data:/var/lib/tarantool
      - ./tarantool.conf.lua:/etc/tarantool/tarantool.conf.lua
    environment:
      TARANTOOL_CONSOLE_PORT: 3301
      TARANTOOL_LISTEN: 3301
    command: tarantool /etc/tarantool/tarantool.conf.lua

  auth:
    build:
      context: ./auth
    ports:
      - "8000:8000"

volumes:
  tarantool_data:
